### ISSUE TITLE
Node.js installation script

### ISSUE THREAD

**Issue by Glavin001** [valencik/cssmuadm#1]
Use https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-an-ubuntu-14-04-server
- [ ] npm
- [ ] cURL
- [ ] NVM

**Comment by valencik** [comment]
Added tasks/install-NodeJS.sh

**Comment by Glavin001** [comment]
For reference: https://github.com/valencik/cssmuadm/blob/master/tasks/install-NodeJS.sh

Thanks, @valencik !

**Comment by valencik** [comment]
Thanks, was writing it from my phone. :)
