### ISSUE TITLE
FreeNAS: Add support for exporting current settings to file

### ISSUE THREAD

**Issue by valencik** [valencik/cssmuadm#6]
The script should be able to handle exporting the current users, groups, rsync tasks, network shares, etc to yaml files.
Ideally this should look at almost all GETs the API can handle.

**Comment by rainbee2214** [comment]
It currently works for rsync tasks, users and groups. I'm still working on adding the others.

**Comment by rainbee2214** [comment]
As of now, it can export all the GETs available into yaml files.

**Comment by valencik** [comment]
Closing as stale/abandoned.
